### ISSUE TITLE
Clarification on Implementation of 1.5cm Offset for Pre-Grasp Poses

### ISSUE THREAD

**Issue by krtxt** [tylerlum/get_a_grip#13]
Hi @tylerlum , thank you for your work!

I am currently working on reproducing the grasp generation process described in the paper, specifically **Step 1: Grasp Generation**. I am referring to the section where it mentions:

"**recover pre-grasp poses with fingertips 1.5cm off the surface instead of on the surface (more clearance aids collision-free motion planning)**."

I have been looking into the /generate_hand_config_dicts.py script, which is mentioned in the documentation as being responsible for generating the pre-grasp configurations. However, I am having difficulty locating where the 1.5cm offset from the object surface is implemented in the code.

Could you please provide some guidance or point me to the specific part of the code where this offset is applied? This would greatly help in ensuring that I am correctly implementing the pre-grasp pose generation as described in the paper.

Thank you for your time and assistance.

**Comment by tylerlum** [comment]
Great question! 

It's here: https://github.com/tylerlum/get_a_grip/blob/0492901c9b997647a78b575b29c761f86c1cf5ec/get_a_grip/dataset_generation/scripts/generate_hand_config_dicts.py#L104

```
    thres_dis: float = 0.015
    thres_pen: float = 0.015
```

the first is the distance that we optimize the desired contact points to. The second is the distance from the object surface that is considered in penetration. Tune these as needed!

**Comment by krtxt** [comment]
Got it! Thank you~
